main:
  - title: Blog
    link: https://blog.ixk.me
  - title: GitHub
    link: https://github.com/syfxlin
  - title: Projects
    link: https://blog.ixk.me/projects
  - title: Friends
    link: https://blog.ixk.me/links
  - title: About
    link: https://blog.ixk.me/about
