language: zh
link: https://ixk.me
logo: /image/config/seo/logo.400x400.jpg
title: Otstar Lin
subtitle: "@syfxlin"
description: >-
  Otstar Lin's Portfolio (Personal Website). Software Developer / Blogger /
  Photography Enthusiast.
birthday: 2017-07-01T00:00
keywords:
  - Otstar Lin
  - syfxlin
  - Blog
  - 博客
  - Java
  - JavaScript
  - TypeScript
  - Full Stack
