# config
locale: zh_Hans
display_url: https://ixk.me
# storage
backend:
  name: github
  repo: syfxlin/home
  branch: master
  base_url: https://netlify-cms-oauth-syfxlin.vercel.app/
local_backend: true
publish_mode: editorial_workflow
# images
media_folder: public/img
public_folder: /img
# collections
collections:
  - name: page
    label: 页面
    folder: content/pages
    create: true
    slug: index
    path: "{{title}}/index"
    preview_path: "/{{fields.slug}}"
    sortable_fields:
      - title
      - date
      - date_updated
    fields:
      - name: title
        label: 标题
        widget: string
      - name: slug
        label: 链接
        widget: string
      - name: layout
        label: 布局
        widget: select
        default: page
        options:
          - value: main
            label: 主页
      - name: date
        label: 时间
        widget: datetime
      - name: body
        label: 内容
        widget: markdown
  - name: settings
    label: 设置
    files:
      - file: content/settings/author.json
        name: author
        label: 作者
        create: true
        delete: false
        fields:
          - name: firstName
            label: 名
            widget: string
          - name: lastName
            label: 姓
            widget: string
          - name: avatar
            label: 头像
            widget: image
          - name: description
            label: 描述
            widget: text
      - file: content/settings/nav.json
        name: nav
        label: 菜单
        create: true
        delete: false
        fields:
          - name: main
            label: 主菜单
            widget: list
            fields:
              - name: title
                label: 标题
                widget: string
              - name: url
                label: 链接
                widget: string
              - name: icon
                label: 图标
                widget: image
              - name: full
                label: 默认显示名称
                widget: boolean
                default: false
      - file: content/settings/seo.json
        name: seo
        label: SEO
        create: true
        delete: false
        fields:
          - name: language
            label: 语言
            widget: string
          - name: url
            label: 站点地址
            widget: string
          - name: title
            label: 站点名称
            widget: string
          - name: description
            label: 站点描述
            widget: text
          - name: logo
            label: 站点图片
            widget: image
          - name: twitter
            label: Twitter
            widget: string
          - name: meta_tags
            label: Meta 标签
            widget: code
            default_language: json
          - name: link_tags
            label: Link 标签
            widget: code
            default_language: json
      - file: content/settings/ga.json
        name: ga
        label: Google Analysis
        create: true
        delete: false
        fields:
          - name: token
            label: Token
            widget: string
