name: Next Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    env:
      TZ: Asia/Shanghai
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install depker-cli
        run: npm i -g @syfxlin/depker-cli
      - name: Login to depker
        run: |
          depker config:endpoint ${{ secrets.DEPKER_ENDPOINT }} &&
          depker login:token ${{ secrets.DEPKER_TOKEN }}
      - name: Deploy to depker
        run: depker deploy -v
