name: Next Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    env:
      TZ: Asia/Shanghai
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: "--force"
          git_remote_url: "ssh://dokku@ixk.me/home"
          ssh_private_key: ${{ secrets.DOKKU_PRIVATE_KEY }}
